### ISSUE TITLE
Create a production preset

### ISSUE THREAD

**Issue by oliviertassinari** [doctolib/babel-preset-doctolib#1]
Here are some intereseted plugin for this purpose
https://github.com/callemall/material-ui/blob/master/docs/src/.babelrc#L4

**Comment by salper** [comment]
Nice catch.

**Comment by neoziro** [comment]
We can create a production preset that inherits from that one :+1:.

**Comment by neoziro** [comment]
Done in 6109f705d2d990c64de722b309b4513f5c021810
